### ISSUE TITLE
Completely matched orders not leaving the book

### ISSUE THREAD

**Issue by MomoCrypto** [Mshuu/SwitchDexIssues#24]
When completely matching an order, often the order that you match stays on the book with 0.000 showing as the available amount. Orders below a certain amount need to be autocancelled I think

**Comment by Mshuu** [comment]
This is a stupid rounding issue with three digits, I've got a fix for it. Should come out in the next update

**Comment by Mshuu** [comment]
This is fixed, awaiting release.
