### ISSUE TITLE
Tokens to add

### ISSUE THREAD

**Issue by MomoCrypto** [Mshuu/SwitchDexIssues#25]
Idex gems:
LTO: 0x3DB6Ba6ab6F95efed1a6E794caD492fAAabF294D
CHX: 0x1460a58096d80a50a2F1f956DDA497611Fa4f165
UBT: 0x8400D94A5cb0fa0D041a3788e395285d61c9ee5e
PCL: 0x0F02e27745e3b6e9e1310d19469e2b5D7B5eC99A

Allbit gems:
VNT: 0xdcc27bbaa14cafd8a6aeb847e1b01c5dffb70935
CNUS: 0x722f2f3eac7e9597c73a593f7cf3de33fbfc3308
PIB: 0x1864ce27e9f7517047933caae530674e8c70b8a7

Twitter:
HXRO: 0x4bD70556ae3F8a6eC6C4080A0C327B24325438f3

Straight out of ico:
FET: 0x1d287cc25dad7ccaf76a26bc660c5f7c8e2a05bd
HARA: not yet distributed, waiting for a listing
Also CELR after token distribution in the next couple days

**Comment by Mshuu** [comment]
Pushed for approval

**Comment by damvo** [comment]
Celr 0x4F9254C83EB525f9FCf346490bbb3ed28a81C667

**Comment by Mshuu** [comment]
Most of this have been added. However you can add them yourself now using the other section :)
