### ISSUE TITLE
A balanced page

### ISSUE THREAD

**Issue by MomoCrypto** [Mshuu/SwitchDexIssues#26]
Where you can see all tokens that you hold in the switchdex contract and in your connected wallet

**Comment by MomoCrypto** [comment]
*balances

**Comment by Mshuu** [comment]
This is a great idea

**Comment by DeltaBalances** [comment]
Not a solution, but a workaround using a 3rd party website.

I added SwitchDex to my [deposited balances tool](https://deltabalances.github.io/), so users can check all balances in 1 page load.

**Comment by Mshuu** [comment]
That's awesome, thanks for that. We actually have a balance page coming out this week (it's on the site already just needs a few tweaks) but this gives people options
