### ISSUE TITLE
Contract addresses need to be displayed

### ISSUE THREAD

**Issue by MomoCrypto** [Mshuu/SwitchDexIssues#28]
Can display it where the depth chart is for now since order books are illiquid and the depth chart is broken anyway. 
You need to display contract addresses for user peace of mind

**Comment by Mshuu** [comment]
Agreed. I'll chat to the designers and find somewhere to put it

**Comment by Mshuu** [comment]
This is fixed in the latest build, not the best positioning but temporary for now
