### ISSUE TITLE
Can not place an order. Using chrome, a ledger nano s and the extension Ublock. 

### ISSUE THREAD

**Issue by CryptoDvK** [Mshuu/SwitchDexIssues#30]

**Comment by melvinalvarez** [comment]
Had the same issue (also using Chrome but with Metamask) while uBlock was enabled. 
I had to disable uBlock for the orders to go through

**Comment by Mshuu** [comment]
Unfortunately, this won't be fixed. UBlock interferes with the ledger signing process and any workaround would make the entire thing less secure.
