### ISSUE TITLE
Error with Ethereum transaction.

### ISSUE THREAD

**Issue by Bobogauntice** [Mshuu/SwitchDexIssues#31]
I keep getting the following error message when trying to deposit ETH or ESH to my SwitchDex wallet: "You tried to send an Ethereum transaction but there was an error. Make sure you have enough ETH in your "Wallet" column to pay for the gas fee. If you already have a pending transaction (enter your address on Etherscan to find out), please wait for it to confirm, or increase your "gas price" (in the upper right dropdown) and try again."

I have enough ETH that I should have plenty remaining when doing a deposit from my ETH wallet to SwitchDex wallet, so that isn't the issue.  I have also raised my "gas price" sufficiently high, but still no luck.  The funds have been in this wallet for days and have been plenty confirmed.  I have also tried Firefox and Chrome.

What else can I do?

**Comment by MomoCrypto** [comment]
What wallet are you using to login? Nano ledger, trust wallet etc? Might help solve the bug

**Comment by Bobogauntice** [comment]
I'm using an eth wallet created using Coinomi. Is that a trust wallet?

**Comment by Mshuu** [comment]
Unfortunately since it's a new wallet we don't support them as of yet. I'll add it to the list to work on but it'll be a bit of a lower priority. You could always move your funds into a temporary wallet for trading using any of the supported wallets (MEW/Switchdex/Mycrpto/Ledger/Trezor)
