### ISSUE TITLE
Units/labels missing on chart's x and y axis

### ISSUE THREAD

**Issue by damvo** [Mshuu/SwitchDexIssues#32]
Especially the bottom one. I think both abscissa and ordinate should be labeled and show units. Kind of confusing right now imo

![PrtScr capture_9](https://user-images.githubusercontent.com/48738338/55155325-f585db00-514e-11e9-8925-dbf756f1a193.jpg)

**Comment by MomoCrypto** [comment]
Yes. I also don’t like the large spacing between the bars

**Comment by Mshuu** [comment]
Agreed.

**Comment by Mshuu** [comment]
This is part of the new design so I'm going to close it out until then.
