### ISSUE TITLE
Under "My balance", could empty fields display a keeword like "value" or "amount"

### ISSUE THREAD

**Issue by damvo** [Mshuu/SwitchDexIssues#33]
Some people have been trying to paste a ERC20 address in those fields instead of a value.
Instead of "ETH", it could display "ETH amount" or whatever term is better, to avoid confusion? Same for other coins.
![image](https://user-images.githubusercontent.com/48738338/55400554-1468e080-5546-11e9-9c55-4e4702ef7782.png)

**Comment by Mshuu** [comment]
Yeah I don't like the descriptor either.

**Comment by Mshuu** [comment]
This is fixed in the latest build :)
