### ISSUE TITLE
Under "My balance", turn the arrow around for withdrawals

### ISSUE THREAD

**Issue by damvo** [Mshuu/SwitchDexIssues#34]
![image](https://user-images.githubusercontent.com/48738338/55400696-79bcd180-5546-11e9-8968-7fcbd22dc038.png)

This arrow illustrates deposits. would make sense if it was pointing to the left when "withdraw" is selected

**Comment by Mshuu** [comment]
It's meant to turn around :) I'll fix it

**Comment by Mshuu** [comment]
We changed this up a bit to make more sense.
