### ISSUE TITLE
Request: having SDEX directly avalaible in the drop down token list

### ISSUE THREAD

**Issue by damvo** [Mshuu/SwitchDexIssues#35]
I understand why ESH is the default token when we reach switchdex.ag, and that it's a marketing/design issue more than a dev issue, but wouldn't it make sense if SDEX was directly promoted in the drop down menu, just before 0ED token? 

Or any other way get more exposure for the SDEX token.

**Comment by Mshuu** [comment]
I agree with this. There's some more ordering options coming so for now it wont change but will shortly :)

**Comment by Mshuu** [comment]
Released in the latest update :)
