### ISSUE TITLE
Request: get rid of the case sensitivity in the url bar

### ISSUE THREAD

**Issue by damvo** [Mshuu/SwitchDexIssues#37]
Don't know if this is possible, it doesn't seem to be a Forkdelta feature.

To illustrate my thoughts:
https://www.binance.com/en/trade/pro/ETH_BTC
and
https://www.binance.com/en/trade/pro/eth_BTC
will both redirect to the ETH/BTC trading page.

On switchdex however, https://switchdex.ag/#esh-ETH won't load.

I personally often navigate through trading pairs by editing the address bar rather than navigating through the usual drop down menu. 

I understand this has a low priority level, if any :)

**Comment by Mshuu** [comment]
This has been done :)
