### ISSUE TITLE
In the buy/sell column, the price isn't correctly labeled

### ISSUE THREAD

**Issue by damvo** [Mshuu/SwitchDexIssues#41]
It's written price TOKEN/BASE instead of BASE/TOKEN

Example:
Should be ETH/ESH rather than ESH/ETH
![PrtScr capture_19](https://user-images.githubusercontent.com/48738338/57450249-46b0e080-725e-11e9-87f7-8c4588558275.jpg)

**Comment by Mshuu** [comment]
This is fixed in the latest build :)
