### ISSUE TITLE
Request: in the drop down menus, extend the clickable zone to the whole width 

### ISSUE THREAD

**Issue by damvo** [Mshuu/SwitchDexIssues#43]
Example:
![PrtScr capture_20](https://user-images.githubusercontent.com/48738338/57525646-8db8d780-732b-11e9-937a-f17c5034ad8a.jpg)
I gotta click on the word DAI if I want to get to the DAI pair. However, if my cursor is placed a bit more right, even though the whole DAI line appears to be active (white color), nothing happens if I click.

Low priority obviously

**Comment by Mshuu** [comment]
Fixed in the latest build :)
